"""Phase 5 飞书确认域。"""

from .candidate_notifier import CandidateFeishuNotifier, CandidateNotifySummary
from .channel_adapter import (
    FeishuChannelBridge,
    FeishuOutboxWorker,
    FeishuPermanentTransportError,
    FeishuRuntimeConfig,
    FeishuTransportError,
    render_candidate_confirmation_card,
)
from .service import (
    ACTION_APPROVE,
    ACTION_REJECT,
    CANDIDATE_CONFIRM,
    INBOX_FAILED,
    INBOX_PROCESSED,
    INBOX_RECEIVED,
    OUTBOX_FAILED,
    OUTBOX_QUEUED,
    OUTBOX_RETRY,
    OUTBOX_SENDING,
    OUTBOX_SENT,
    CandidateCardEnvelope,
    ClaimedOutbox,
    FeishuCandidateCardService,
    FeishuInboxService,
    FeishuOutboxStore,
    FeishuStateError,
    InboxActionResult,
)

__all__ = [
    "ACTION_APPROVE",
    "ACTION_REJECT",
    "CANDIDATE_CONFIRM",
    "INBOX_FAILED",
    "INBOX_PROCESSED",
    "INBOX_RECEIVED",
    "OUTBOX_FAILED",
    "OUTBOX_QUEUED",
    "OUTBOX_RETRY",
    "OUTBOX_SENDING",
    "OUTBOX_SENT",
    "CandidateCardEnvelope",
    "ClaimedOutbox",
    "FeishuCandidateCardService",
    "FeishuInboxService",
    "FeishuOutboxStore",
    "FeishuStateError",
    "InboxActionResult",
    "CandidateFeishuNotifier",
    "CandidateNotifySummary",
    "FeishuRuntimeConfig",
    "FeishuChannelBridge",
    "FeishuOutboxWorker",
    "FeishuTransportError",
    "FeishuPermanentTransportError",
    "render_candidate_confirmation_card",
]
